//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.08.07 at 01:52:16 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://task1.kirova.htp.by", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.htp.kirova.task1.entity;
